### ISSUE TITLE
Net::SSH::Perl doesn't respect ConnectTimeout option

### ISSUE THREAD

**Issue by jobman-mike** [lkinley/Net-SSH-Perl#17]
Net::SSH::Perl seems to ignore "ConnectTimeout" and proceeds to hang for a while.
This makes it tricky to use with  a batch of servers (When one stops responding)

E.g:

    my $ssh    = Net::SSH::Perl->new($_, options => [
    "Compression $UseCompression",
    "Port $port",
    "IdentityFile $IdentityFile",
    "BatchMode yes",
    "ConnectTimeout=5"]);

Is this likely to be something that can easily be resolved?

**Comment by briandfoy** [comment]
I've forked this project at [briandfoy/net-ssh-perl](https://github.com/briandfoy/net-ssh-perl), and you can reopen this issue there if you'd like.  Otherwise, I'll add it myself at some later time. See #22.

If you include text like `transferred from linkley/Net-SSH-Perl#17`, GitHub should make a reference between the two issues. You should see such a reference in this issue now.

I don't have a fix for this issue, but can merge someone else's work.

**Comment by jobman-mike** [comment]
Sorry for leaving this open so long, I ended up using Net::OpenSSH.

**Comment by briandfoy** [comment]
I think Net::OpenSSH is the correct answer. Good luck.
