### ISSUE TITLE
Release latest version to CPAN?

### ISSUE THREAD

**Issue by iynehz** [lkinley/Net-SSH-Perl#6]
I see this repo has version 2.07, but on CPAN it is still 2.01 now https://metacpan.org/pod/Net::SSH::Perl

**Comment by lkinley** [comment]
Unfortunately, I don't manage the CPAN releases.  I'll ping the person who does and request it.

**Comment by renormalist** [comment]
It's me. And I actually would just have to do it. Sorry. There is no real reason blocking it besides needing an hour of concentration...

**Comment by jwrightecs** [comment]
Still at 2.01 on CPAN, any update on when this will be updated there?

**Comment by renormalist** [comment]
This weekend.
Viele Grüße,Steffen-- 
<steffen.schwigon@gmx.de>

-------- Ursprüngliche Nachricht --------
Von: jwrightecs <notifications@github.com> 
Datum: 03.03.2017  15:30  (GMT+01:00) 
An: lkinley/Net-SSH-Perl <Net-SSH-Perl@noreply.github.com> 
Cc: Steffen Schwigon <ss5@renormalist.net>, Comment <comment@noreply.github.com> 
Betreff: Re: [lkinley/Net-SSH-Perl] Release latest version to CPAN? (#6) 

Still at 2.01 on CPAN, any update on when this will be updated there?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/lkinley/Net-SSH-Perl","title":"lkinley/Net-SSH-Perl","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/lkinley/Net-SSH-Perl"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jwrightecs in #6: Still at 2.01 on CPAN, any update on when this will be updated there?"}],"action":{"name":"View Issue","url":"https://github.com/lkinley/Net-SSH-Perl/issues/6#issuecomment-283967418"}}}

**Comment by renormalist** [comment]
2.09 is on its way to CPAN.

It is basically lkinley's version. However, in the past I merged in some release polishing from all the release I did before lkinley picked it up with  the hard parts. This is *not* done yet, although I still used my auxiliary branches over there in renormalist/Net-SSH-Perl. I will review that later together with test results from CPANTESTERS.

Currently I even tend to throw away my repos and switching over to lkinleys repository completely --  probably after some pull requests to sync some useful parts of my history, like POD errors, intermediate release changelogs, etc.

If anyone thinks that's a stupid idea, I'm all ears.
